#!/bin/bash
set -e

# https://www.linode.com/docs/development/perl/manage-cpan-modules-with-cpan-minus/

if ((EUID == 0))
then
    apt-get update
    apt-get install curl build-essential libssl-dev
else
    if [[ $HOME != /home/$USER ]]
    then
        echo "Homedir not correctly set (got homedir '$HOME' for user '$USER')" >&2
        exit 29
    fi

    squiggledir="$(eval echo "~$USER")"
    if [[ $squiggledir != /home/$USER ]]
    then
        echo "~ not correctly set (got ~ '$squiggledir' for user '$USER')" >&2
        exit 30
    fi
fi

echo "USER: $USER"
echo "HOME: $HOME"


which cpanm > /dev/null && return 0
# can't re-run this for admin user, can't figure out how to make it work
curl -L https://cpanmin.us | perl - --sudo App::cpanminus

cpanm --self-upgrade --sudo

cpanm --local-lib=~/perl5 local::lib

